// App translations and static configuration

export const INITIAL_SETTINGS = {
  restaurantNameEn: "M4D CAFE",
  restaurantNameAr: "M4D CAFE",
  branchNameAr: "الفرع الرئيسي",
  taxId: "123-456-789",
  addressAr: "15 شارع الجمهورية، القاهرة",
  phone: "02-12345678",
  taxRate: 0,
  serviceRate: 0.12,
  currencyEn: "EGP",
  currencyAr: "ج.م",
  printerName: "Default",
  printFormat: "thermal" as const,
  autoBackup: true,
  defaultAutoPrint: true,
  defaultCompactView: false,
  adminUsername: "elmashad",
  adminPassword: "elmashad@123"
};

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    pos: "POS System",
    kitchen: "Kitchen KDS",
    tables: "Tables Management",
    categories: "Categories",
    menu: "Menu Items",
    inventory: "Inventory",
    warehouses: "Warehouses",
    purchases: "Purchases",
    suppliers: "Suppliers",
    treasury: "Treasury",
    customers: "Customers",
    employees: "Staff Management",
    reports: "Financials",
    settings: "System Settings",
    logout: "Sign Out",
    all: "All Items",
    search: "Search Menu...",
    autoPrint: "Auto Print",
    "dine-in": "Dine In",
    takeaway: "Take Away",
    delivery: "Delivery",
    receiptVoucher: "Receipt",
    paymentVoucher: "Payment",
    receivedFrom: "Received From",
    paidTo: "Paid To",
    success: "Success",
    variants: "Options",
    addons: "Add-ons",
    purchasesReport: "Purchases",
    treasuryReport: "Cashier",
    profitAndLoss: "Profit & Loss",
    expensesReport: "Expenses",
    thermal: "Thermal (80mm)",
    a4: "A4 Paper",
    nameArLabel: "Arabic Name",
    nameEnLabel: "English Name",
    holdOrder: "Hold Order",
    resumeOrder: "Resume",
    itemNotes: "Special Request",
    commandSearch: "Search Function (Ctrl+K)...",
    totalSales: "Total Sales",
    totalOrders: "Orders Count",
    lowStock: "Low Stock",
    menuDist: "Menu Distribution",
    salesHistory: "Recent Sales",
    name: "Name",
    stock: "Stock Level",
    noAlerts: "No Alerts",
    noSales: "No sales recorded",
    total: "Total Amount",
    action: "Control",
    invPurchases: "Operations",
    empTreasury: "Accounts",
    admin: "Manager",
    active: "Active",
    inactive: "On Leave",
    add: "Add New",
    addEmployee: "Add Staff",
    role: "Position",
    salary: "Salary",
    phone: "Contact",
    nameAr: "Name (AR)",
    nameEn: "Name (EN)",
    cancel: "Cancel",
    save: "Save Changes",
    taxService: "Tax & Identity",
    tax: "VAT",
    backup: "Data Protection",
    printers: "Devices",
    signIn: "Login",
    signInMsg: "Enter credentials to start",
    username: "User ID",
    password: "Password",
    addItem: "New Item",
    category: "Section",
    supplier: "Provider",
    invoiceNum: "Invoice #",
    addPurchase: "New Purchase",
    payDebt: "Settlement",
    balance: "Balance Due",
    amount: "Value",
    income: "Income",
    expense: "Expense",
    description: "Memo",
    date: "Date",
    items: "SKUs",
    pay: "Complete",
    grossSales: "Gross Total",
    netSales: "Net Total",
    export: "Export XLS",
    print: "Print Now",
    thankYou: "Thanks for your visit!",
    card: "Visa/Debit",
    cash: "Cash Money",
    credit: "Account",
    payroll: "Payroll",
    supplierAccounts: "Supplier Accounts",
    type: "Type",
    location: "Location",
    address: "Address",
    price: "Price"
  },
  ar: {
    dashboard: "لوحة التحكم",
    pos: "نقطة البيع",
    kitchen: "المطبخ (KDS)",
    tables: "إدارة الطاولات",
    categories: "الأقسام",
    menu: "قائمة الطعام",
    inventory: "المخزون",
    warehouses: "المخازن",
    purchases: "المشتريات",
    suppliers: "الموردين",
    treasury: "الخزينة",
    customers: "العملاء",
    employees: "الموظفين",
    reports: "التقارير",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    all: "الكل",
    search: "بحث في المنيو...",
    autoPrint: "طباعة تلقائية",
    "dine-in": "صالة",
    takeaway: "تيك أواي",
    delivery: "دليفري",
    receiptVoucher: "سند قبض",
    paymentVoucher: "سند صرف",
    receivedFrom: "استلمنا من",
    paidTo: "صرفنا إلى",
    success: "تمت العملية بنجاح",
    variants: "الخيارات",
    addons: "الإضافات",
    purchasesReport: "المشتريات",
    treasuryReport: "الخزينة",
    profitAndLoss: "الأرباح والخسائر",
    expensesReport: "المصروفات",
    thermal: "حراري (٨٠ ملم)",
    a4: "ورق عادي A4",
    nameArLabel: "الاسم بالعربي",
    nameEnLabel: "الاسم بالإنجليزي",
    holdOrder: "تعليق الطلب",
    resumeOrder: "استئناف",
    itemNotes: "ملاحظات الطلب",
    commandSearch: "ابحث عن وظيفة (Ctrl+K)...",
    totalSales: "إجمالي المبيعات",
    totalOrders: "عدد الطلبات",
    lowStock: "النواقص",
    menuDist: "توزيع المنيو",
    salesHistory: "آخر المبيعات",
    name: "الاسم",
    stock: "المخزون",
    noAlerts: "لا توجد تنبيهات",
    noSales: "لا توجد مبيعات",
    total: "الإجمالي",
    action: "إجراء",
    invPurchases: "العمليات",
    empTreasury: "الحسابات",
    admin: "مدير",
    active: "نشط",
    inactive: "في إجازة",
    add: "إضافة جديد",
    addEmployee: "إضافة موظف",
    role: "الوظيفة",
    salary: "الراتب",
    phone: "الموبايل",
    nameAr: "الاسم بالعربي",
    nameEn: "الاسم بالإنجليزي",
    cancel: "إلغاء",
    save: "حفظ التغييرات",
    taxService: "الهوية والضرائب",
    tax: "الضرائب",
    backup: "حماية البيانات",
    printers: "الأجهزة والطابعات",
    signIn: "دخول",
    signInMsg: "سجل دخولك لبدء العمل",
    username: "المستخدم",
    password: "كلمة المرور",
    addItem: "صنف جديد",
    category: "القسم",
    supplier: "المورد",
    invoiceNum: "رقم الفاتورة",
    addPurchase: "فاتورة شراء",
    payDebt: "سداد مديونية",
    balance: "الرصيد",
    amount: "المبلغ",
    income: "إيرادات",
    expense: "مصروفات",
    description: "البيان",
    date: "التاريخ",
    items: "أصناف",
    pay: "دفع وإتمام",
    grossSales: "الإجمالي العام",
    netSales: "الصافي",
    export: "تصدير XLS",
    print: "طباعة",
    thankYou: "شكراً لزيارتكم!",
    card: "فيزا/كارت",
    cash: "كاش",
    credit: "آجل",
    payroll: "مسيرات الرواتب",
    supplierAccounts: "حسابات الموردين",
    type: "النوع",
    location: "الموقع",
    address: "العنوان",
    price: "السعر"
  }
};
